### ISSUE TITLE
Questions from Raquel

### ISSUE THREAD

**Issue by fetmar** [ICTatRTI/coconut#20]
-   How well see in the database the subject of the questions if we don’t have a number assign in the question? We’ll have a key word?
-   Could we save the PS if it has questions left with no answer?

**Comment by carl-fisher** [comment]
Wayne says: 
- Question numbers will work to identify the questions, if they're available.
- Questions that feed the Unique ID cannot be left blank or be NR.

**Comment by vbakalov** [comment]
We number the questions and we added "No responde" to ensure the question is answered.
