### ISSUE TITLE
"Menú principal" or "Main menu" replaces main menu when window is resized

### ISSUE THREAD

**Issue by carl-fisher** [ICTatRTI/coconut#23]
If the site window is made narrower, at some point the main menu is replaced with the text "Main menu".  The menu should always be displayed.

**Comment by gmcressman** [comment]
This is normal designed behavior of the adaptive theme. Click on "Main menu" and you will find that it has become a dropdown. Try the site on your smartphone to see why this makes sense in a responsive design.

**Comment by carl-fisher** [comment]
It switches when it's still awfully wide- it's quite unexpected, with no hints as to what you should do.  In Spanish mode the menu has already wrapped to 2 lines but the English is still on 1 line with some room to spare.
