### ISSUE TITLE
Reg: Geographic drill down problems

### ISSUE THREAD

**Issue by fetmar** [ICTatRTI/coconut#38]
Orden of “Direccion”, keep the same as the RF: calle y numero, barrio, municipio, provincial.

**Comment by fetmar** [comment]
The form works to only allow people to select a city if it's in the right province. If we don't keep this order then they have to enter the information backwards on the form. The client is asking for two different things.

**Comment by carl-fisher** [comment]
Wayne says: "If I understand correctly, we should make the on-line system logical so that the drop down lists will work. It will be a pain for data entry in the beginning. We can adjust the paper forms later."

**Comment by vbakalov** [comment]
The system present the order so the auto-complete works.
