### ISSUE TITLE
Add notification if you skip a question

### ISSUE THREAD

**Issue by fetmar** [ICTatRTI/coconut#5]
When I jump to a question and I forgot to answer the one before that. Could we put a notice? Or it shows at the end?

**Comment by vbakalov** [comment]
We need to know which questions are required. It will show error on questions that are required and are not answered, otherwise it will not.

**Comment by fetmar** [comment]
This will take time to develop and more detailed specifications about how it should behave. Currently the complete button will mark all the previous questions that we have marked as required.

**Comment by carl-fisher** [comment]
This is similar to #20 - we will provide a list of questions that have not been responded to.

**Comment by vbakalov** [comment]
We added "No responde" to the questions to check if answered.
