### ISSUE TITLE
Participant Reg chokes on calle y numero

### ISSUE THREAD

**Issue by carl-fisher** [ICTatRTI/coconut#56]
Enter data as follows:

Fecha: 10/28/2013
Nombre: a
Apellido: a
Apodo: a
calle y numero: 12 abc
provincia: SANTIAGO
municipio: SANTIAGO DE LOS CABALLEROS
barrio: SABANA IGLESIA
dia: 1
mes: enero
ano: 1987
sexo: M
telefono cellular: No
telefono en casa: No
correo electronico: No
nombre de persona: a
relacionada: a
telefono: 809 123-4567

Click on Completado.  The form scrolls up to the calle y numero field.  No error.

If I change relacionada to esposa I can get the checkmark, but I cannot advance off the form to where it asks me what I want to do next.

**Comment by vbakalov** [comment]
Fixed. There was issue with validating the group question.
