### ISSUE TITLE
Make sure skip logic is correct for 14. ¿sabes leer y escribir?

### ISSUE THREAD

**Issue by fetmar** [ICTatRTI/coconut#9]
Could we include the jumps between questions? For example sabes leer y escribir? If you answer NO you go to #24. If you answer yes, it displays all the questions in education. This could prevent mistakes in data entry and makes the page looks cleaner.

**Comment by vbakalov** [comment]
I tried to fix this but if I put skip_logic on Q17, Q17 will not display but it needs to displayregardless of answer to 14.

**Comment by vbakalov** [comment]
I think we can close this since it cannot "jump" but the the effect is the same since Q17 is the next question in case of Q14"No".

**Comment by fetmar** [comment]
The form specifications say that we should skip to 17 if they answer no to 14. That's what we're going with so far. If we need to change that we need confirmation and new specifications.

**Comment by fetmar** [comment]
This was addressed
